print_info() {
    # info title
    # info underline

    info "os" distro
    # info "Host" model
    # info "Kernel" kernel
    info "pkgs" packages
    info "up" uptime
    # info "Shell" shell
    # info "Resolution" resolution
    info "de" de
    # info "WM" wm
    # info "WM Theme" wm_theme
    # info "Theme" theme
    # info "Icons" icons
    info "term" term
    # info "Terminal Font" term_font
    info underline
    info "CPU" cpu
    info "GPU" gpu
    info "RAM" memory

    # info "GPU Driver" gpu_driver  # Linux/macOS only
    # info "CPU Usage" cpu_usage
    # info "Disk" disk
    # info "Battery" battery
    # info "Font" font
    # info "Song" song
    # [[ "$player" ]] && prin "Music Player" "$player"
    # info "Local IP" local_ip
    # info "Public IP" public_ip
    # info "Users" users
    # info "Locale" locale  # This only works on glibc systems.

    # info cols
}


ascii_distro="Arch_small"
