#Colors
include ~/.config/kitty/colorshemes/monochromatic.conf

# Fuente principal
font_family JetBrainsMono Nerd Font
bold_font JetBrainsMono Nerd Font
italic_font JetBrainsMono Nerd Font
bold_italic_font JetBrainsMono Nerd Font

# Estilos
font_style Regular
bold_font_style Bold
italic_font_style Italic
bold_italic_font_style Bold Italic

# Tamaño de fuente
font_size 10.0

# Opcional: ligaduras y mejoras visuales
enable_ligatures yes

adjust_line_height 0
adjust_column_width 0
box_drawing_scale 0.001, 1, 1.5, 2

# Cursor
shell_integration no-cursor
cursor_shape     block
cursor_blink_interval 0
cursor_shape_unfocused hollow
cursor_beam_thickness 1.9
cursor_stop_blinking_after 15.0

# Scrollback
scrollback_lines 1000
scrollback_pager /usr/bin/less
wheel_scroll_multiplier 5.0

# URLs
url_style double
url_color #0000FF    
detect_urls yes       
open_url_modifiers ctrl+shift
open_url_with firefox
underline_hyperlinks hover 
url_style straight   
copy_on_select yes
clear_selection_on_clipboard_loss no


# Shell
shell bash
close_on_child_death no
allow_remote_control yes
term xterm-256color

# Bell
visual_bell_duration 0.0
enable_audio_bell no

# Window
remember_window_size   no
initial_window_width   700
initial_window_height  400
window_border_width 1.5
window_margin_width 2
window_padding_width 2
inactive_text_alpha 1.0
background_opacity 1.0
draw_minimal_borders yes

# Performance
repaint_delay    20
input_delay 2
sync_to_monitor no

#new
disable_ligatures never
placement_strategy center
dim_opacity 0.60
dynamic_background_opacity no

#bell
enable_audio_bell no
visual_bell_duration 0.0
visual_bell_color none
window_alert_on_bell no
bell_on_tab ""
command_on_bell none
bell_path none
linux_bell_theme __custom

#No map
map ctrl+shift+n no_op
map ctrl+shift+t no_op
map ctrl+shift+l no_op
map ctrl+shift+h no_op
map ctrl+shift+j no_op
map ctrl+shift+k no_op
map ctrl+shift+backslash no_op
map ctrl+shift+right no_op
map ctrl+shift+left no_op
map ctrl+shift+up no_op
map ctrl+shift+down no_op
map ctrl+shift+enter no_op
map ctrl+shift+q no_op
map ctrl+alt+tab    no_op
map ctrl+alt+shift+tab no_op

