##############
# globarl optins
#############
set -g default-shell /usr/bin/zsh
setw -g xterm-keys on
setw -g mode-keys vi
set -as terminal-overrides ",alacritty*:Tc"

##############
# statusbar
#############
set -g status-position top
set -g status-right-length 50
set -g status-left-length 50
set -g status-left ''
set -g status-right '[#S]'
set -g status-justify right
set -g status-interval 1
setw -g window-status-separator ""
set -g status-style bg=terminal
set -g status-bg "#121212"
set -g status-fg "#ffffff"
set -g set-clipboard on
set-window-option -g mode-style bg=colour8,fg=white
set -g message-style bg=black,fg=white
setw -g window-status-format "#[bg=black,fg=colour8]#[bg="#222222",fg=terminal] #I #[bg="#222222",fg=terminal]#W #[bg=black,fg=colour8, nobold]"
setw -g window-status-current-format "#[bg=terminal,fg=black]#[bg="#b9b9b9",fg="#222222",bold] #I #[bg="#b9b9b9",fg="#222222",bold]#W #[bg=terminal,fg=black, bold]"
# set -g status-left '#[bg=colour8,fg=terminal]#{?client_prefix,  •  ,}'
set -g status-left '#[bg=colour8,fg=terminal]#{?client_prefix,  +  ,}'
set -g status-justify left
set -g set-titles on
set -g set-titles-string "#W"
set -g pane-active-border-style fg=terminal,bold
set -g pane-border-style fg=colour8,dim,overline
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set -g mouse on
# set-window-option -g pane-border-status top
# set-window-option -g pane-border-format "#[align=left]#[fg=dim]─ #{s|$HOME|~|:pane_current_path} ─"

# If running inside tmux ($TMUX is set), then change the status line to red
%if #{TMUX}
set -g status-bg red
%endif

##############
# Scrollback 
#############
set -g history-limit 10000
set-window-option -g visual-bell off
set-window-option -g bell-action any
set -g remain-on-exit off	
set -g renumber-windows on


##############
# change prefix 
#############
set -g prefix C-Space
bind C-Space send-prefix

##############
# unbind 
#############
unbind %
unbind \"
unbind x
unbind &
unbind C-b
unbind c
unbind n
unbind p
unbind u


##############
# key tmux 
#############

#####
#  Navegation
#####
###### Navegation between tabs
bind -n M-o select-window -n
###### Navegation between panels
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

#####
#  create
#####
bind-key -n C-t new-window
bind -n C-k new-window
bind k new-window
##### Create panels
bind Enter split-window -h -c "#{pane_current_path}"
# create panel -h
bind M-Enter split-window -v -c "#{pane_current_path}"

#####
#  close
#####
bind-key -n C-w if-shell '[ "$(tmux list-panes | wc -l)" -gt 1 ]' 'kill-pane' 'kill-window'
bind -n M-q if-shell '[ "$(tmux list-panes | wc -l)" -gt 1 ]' 'kill-pane' 'kill-window'

#####
#  resize
#####
######  resize panels
bind -n C-M-h resize-pane -L 5
bind -n C-M-j resize-pane -D 5
bind -n C-M-k resize-pane -U 5
bind -n C-M-l resize-pane -R 5

#####
#  rename
#####
bind -n M-n command-prompt "rename-window '%%'"

#####
#  copy-mode
#####
## open mode vim
bind -n M-u if-shell -F '#{pane_in_mode}' 'send-keys q' 'copy-mode'
#### copy text or buffer
bind-key -T copy-mode-vi 'y' send -X copy-selection
#### paste text or buffer
bind -n M-p run-shell "tmux send-keys -l \"$(tmux show-buffer)\""
### Visual toggle
set -g @visual_mode "off"
bind -T copy-mode-vi v run-shell '
  if [ "$(tmux show -gqv @visual_mode)" = "line" ]; then
    tmux set -g @visual_mode "char"
    tmux send -X select-pane
    tmux send -X begin-selection
  else
    tmux set -g @visual_mode "line"
    tmux send -X select-line
  fi
'
bind -T copy-mode-vi q run-shell 'tmux set -g @visual_mode "off"; tmux send -X cancel'
bind -T copy-mode-vi Escape run-shell 'tmux set -g @visual_mode "off"; tmux send -X cancel'

#####
#  synchronize
#####
bind -n M-c set synchronize-panes


